[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=kobold-powersave
balanced=balanced
performance=throughput-performance

[battery]
balanced=balanced-battery
power-saver=kobold-powersave
