[main]
dns=systemd-resolved

[connection]
connection.llmnr=0
connection.mdns=0
connection.dns-over-tls=1
connection.dnssec=1
ipv4.dhcp-send-hostname=false
ipv6.dhcp-send-hostname=false
ipv4.dhcp-client-id=stable
ipv6.dhcp-duid=stable-uuid
ipv6.ip6-privacy=2
wifi.powersave=3
wifi.cloned-mac-address=stable-ssid

[device]
wifi.scan-rand-mac-address=yes

[connectivity]
enabled=false
